### ISSUE TITLE
HMR ( Hot module replacement/ Hot Reload ) Not Working Correctly

### ISSUE THREAD

**Issue by DmacMcgreg** [Toilal/vue-webpack-template#10]
To reproduce:
1. Add an input, and bind it to a counter model.
2. Add a button to increment the counter, and increment it to something greater than 1.
3. Add a new variable in any component.
4. Save the file.
5. The state is not preserved. The counter goes back to 1.

**Comment by Toilal** [comment]
I don't think it's supposed to keep the internal state of the component beeing reloaded. Can you make this use case work properly with vue-loader ? ( `.vue` single component files)

IMHO, I think state is preserved for others components in the page, but actually the component beeing reloaded can't keep it's state.

**Comment by DmacMcgreg** [comment]
It works if you look at the vue-cli docs. I have tested it myself and it does seem to work.
This would be the ideal situation, as the way it works now is not true Hot Module Replacement.

![image](http://blog.evanyou.me/images/vue-hot.gif)

**Comment by Toilal** [comment]
Ok, so i'll try to implement this :)

**Comment by DmacMcgreg** [comment]
Cheers, friend!

**Comment by Toilal** [comment]
I confirm it works with official webpack template when modifying the template only. If script part of the component is modified, it's internal state is lost.

**Comment by Toilal** [comment]
I just tested with both JavaScript and TypeScript using this template, and it works exactly like with official webpack template and single file components `.vue` files.

When changes are made in the template or the style of the component, it keeps the internal state of the component. But when changes are made in the script code, it's lost.

Vue doesn't provide support to keep internal state of component when modifying the script part from component. (and it seems imho impossible)

**Comment by DmacMcgreg** [comment]
Thank you for your investigation into the issue.
I was indeed incorrect about it saving state when editing the javascript.

However, when working with this template, I am not able to maintain the state when editing the html only.

Here is a GIF demonstrating the issue (also notice that the compilation takes quite a while for some reason.)

![hot reloading not working](https://cloud.githubusercontent.com/assets/3266023/24656948/78dc4722-1912-11e7-92cb-4b5b77ccb566.gif)

**Comment by Toilal** [comment]
Can you post your whole project in a github repository ? I'll give a look.

Hot Module Reload can be broken because of some babel configuration. You must keep ES2015 modules in babel output (that's why `.babelrc` includes a `{module: false}` option in env preset)

**Comment by DmacMcgreg** [comment]
Hi @Toilal 
I have just cloned your repo vue-webpack-ts-upgrade in this example, but the current repo does the same thing. I have not changed any settings.

**Comment by Toilal** [comment]
vue-webpack-ts-upgrade ?

**Comment by DmacMcgreg** [comment]
Sorry, I have confused another project for yours. I will test out HMR for your project. Apologies if this is the case!!

**Comment by Toilal** [comment]
No problem :) I really think it's working here, but please give it a try ! 

It has also clarified what's the expected behavior for everybody : It should keep state if changing CSS or HTML, but state is lost when component code changes. Anyway, it should never reload the whole browser, and state from other components in the page should be kept intact.

**Comment by DmacMcgreg** [comment]
@Toilal 
Thank you for your help. I have confirmed it is working, although when I edit in Sublime Text, it does not seem to swap the changes out. I think it has to do with some temporary file it creates on save... 


It's a shame though that we can't get it to work like in the following image with React:

![image](http://matthewlehner.net/images/react-hmr-f51607a1.gif)

**Comment by Toilal** [comment]
Yes, it's insane :). But I can't try to support this in this project, maybe this could be asked in https://github.com/vuejs/vue-hot-reload-api.
