### ISSUE TITLE
Running unit tests on JavaScript projects display "Could not find source map for: ..."

### ISSUE THREAD

**Issue by Toilal** [Toilal/vue-webpack-template#14]
When generating a JavaScript project, running unit test is working, but it displays some messages.

Could not find source map for: "/home/travis/build/Toilal/vue-webpack-template/tests/js-default/src/App.vue.js"

I think it's because unit tests run on node v6 and babel do nothing on the input files, so it doesn't generate any sourcemap ?

Any idea @dvic ? Maybe there's an option to disable this warning ?

**Comment by dvic** [comment]
Hmm not sure about this one.

**Comment by Toilal** [comment]
Not really blocking, as the test are still OK and code coverage seems valid too.
