### ISSUE TITLE
Should eslint also check test/unit/karma.conf.js ?

### ISSUE THREAD

**Issue by dvic** [Toilal/vue-webpack-template#16]

**Comment by Toilal** [comment]
Yes, it should. But I think it's the case actually, isn't it ?

**Comment by Toilal** [comment]
Do you think it should be excluded from linting ?

**Comment by dvic** [comment]
No I think it's good to have it included in the linting, currently it's not included. Only files in `src`, `test/unit/specs`, and `test/e2e/specs` are checked. At least that's what it say in `package.json`. I can update this later in the evening.

**Comment by dvic** [comment]
Hmm, I just checked and indeed the `karma.conf.js` is not checked. In order to let it 'pass' many expressions are to be written in es6 syntax (`const` vs `var`, short-hand methods instead of regular functions, etc.) Is this ok or should we ignore karma.conf.js and other future files in `test/unit/*.js`? The changes will work with node 6 but I'm not sure about other node versions.

**Comment by Toilal** [comment]
I think we should stick to upstream behaviour, to minize work for future
merges.

**Comment by dvic** [comment]
True, wasn't thinking about that 👍
