### ISSUE TITLE
Consider bringing back to vue file support?

### ISSUE THREAD

**Issue by mgenware** [Toilal/vue-webpack-template#21]
Thanks for this great project, by far the most reliable and up-to-date Typescript template for vue.

I ran into an issue while importing a third-party component:
```js
import SomeComponent from 'blablabla/src/componentA');
```

The file `componentA` is written in .vue, so running `npm run dev` gives "This dependency was not found", it seems that the loaders used to process the .vue files are removed in this project.

**Comment by Toilal** [comment]
I agree, I should bring it back because I hit this issue too.

User should be able to use in the same project both vue files and vanilla ts/css/template files. I'll merge back vue-loader support from official vuesjs-templates/webpack.

**Comment by Toilal** [comment]
@mgenware I wrote a pull request for this, but I currently do have time to test it that much. Maybe you could give it a try ?

**Comment by Toilal** [comment]
To support importing `.vue` components from standard `.ts` files, I also need to switch back to ts-loader. I'll introduce the brand new [fork-ts-checker-webpack-plugin](https://github.com/Realytics/fork-ts-checker-webpack-plugin) that seems to do what awesome-typescript-loader do while still using official typescript loader.

**Comment by mgenware** [comment]
Awesome, thank you, I'm on a trip, will try it later 😃
