### ISSUE TITLE
transpile ts file to normal vue file (with template, script, style tags)

### ISSUE THREAD

**Issue by iztsv** [Toilal/vue-webpack-template#25]
Hello @Toilal !
I'am beginner in vue and webpack.  I've just used your template and it's awesome.
But I want to replace **karma+mocha+chai** unit testing to [Jest](https://facebook.github.io/jest/). In this case I need to transpile component ts file to 'normal' vue flies which contains <template>, <script> and <style> tags with corresponding content. After that I will be able to use Jest like described in this [article](https://hackernoon.com/jest-for-all-episode-1-vue-js-d616bccbe186).

May be you have any idea how to do this in your template. I will be very happy for any suggestion :)

Thanks in advance!

**Comment by Toilal** [comment]
I don't know Jest test runner, but it should be possible to configure it to load components from `.ts` files without having to transpile them to `.vue` files.

I think it's out of the scope of this template, so i'll close this issue.

**Comment by Trainmaster** [comment]
@ilyaztsv Have you found a way to use this template and Jest?

I'm also struggling getting it to work: `Cannot find module './testComponent.html?style=./testComponent.css' from 'testComponent.vue.ts'`
