### ISSUE TITLE
Feature suggestion: Add service-worker support

### ISSUE THREAD

**Issue by u3u** [Toilal/vue-webpack-template#28]
Hello!
it would be very helpfully if your template have another one ask when initiated "Service worker support (Y/n)?"

And if I set "Yes" some steps should be performed:

add serviceworker-webpack-plugin to package.json dependency
/test/unit/index.js should exclude src/sw.js
karma.conf.js should configure to allow register sw.js from test
is it possible? thanks!

**Comment by Toilal** [comment]
I would consider a pull request for this feature, but using https://github.com/NekR/offline-plugin instead.
