### ISSUE TITLE
scss support?

### ISSUE THREAD

**Issue by dlangerenken** [Toilal/vue-webpack-template#29]
Changing Hello.vue.ts import WithRender to

`import WithRender from './Hello.html?style=./Hello.scss';` (and renaming the css file to scss)

results in:

> This relative module was not found:
> 
> * ../../node_modules/vue-template-loader/lib/scoped-style-loader.js?id=data-v-4215efb4!./Hello.scss in ./src/components/Hello.html?style=./Hello.scss

**Comment by AbeBaehaki** [comment]
If you want to use scss with this template, you will have to install the `sass-loader` and `node-sass` from npm to your dev dependencies. That should make it works.

**Comment by Toilal** [comment]
Have you solved your issue @dlangerenken ? It should work, I use SCSS with this template.
