### ISSUE TITLE
Add support for library projects

### ISSUE THREAD

**Issue by Toilal** [Toilal/vue-webpack-template#3]
Library project with 2 outputs : library and demo.

**Comment by dvic** [comment]
Do you think this should go in the same template? (asking a question whether the user wants a library or an app?)

**Comment by Toilal** [comment]
Yes, I think it should be in the same template, but during generation we need to generate most files in `./demo/` instead of `./src/`, and it's not possible with actual vue-cli version. 

I have a [Pull Request](https://github.com/vuejs/vue-cli/pull/428) on vue-cli to support extending metalsmith (the generator used under the hoods for vue-init).

Alternative that will work with actual vue-cli release is to duplicate `./src` files into `./demo` and use vue-cli filters, until this pull request is merged and released.

**Comment by wilsonsergio2500** [comment]
Yellow, I went thru the vue-cli installer, and when I do npm run dev.. I get Failed to compile, these dependencies were not found -- ./src/App.html?style=./App.css. What am I missing?

**Comment by Toilal** [comment]
A library should also be published as a single file CommonJS ES5 bundle in `package.json` `main` property, and as ES2015 modules in `module` property.

**Comment by Toilal** [comment]
vue-cli has been released with my Pull Request merged, so i'll be able to work on this now.

**Comment by Toilal** [comment]
It's here ! @dvic if you are still here, maybe you can give it a try ?

**Comment by dvic** [comment]
Hi! Looks good, thanks! I'm really looking forward to Vue 2.5: https://medium.com/the-vue-point/upcoming-typescript-changes-in-vue-2-5-e9bd7e2ecf08 (see https://github.com/vuejs/vue/pull/6391).

**Comment by Toilal** [comment]
Yes, I read this article too. When it's out, i'll upgrade this boilerplate.

**Comment by Toilal** [comment]
@dvic => 2.5 is out : https://github.com/vuejs/vue/releases
