### ISSUE TITLE
Unexpected Token : (colon)

### ISSUE THREAD

**Issue by MarcoHeumann** [Toilal/vue-webpack-template#60]
When using any form of

`variable: type;`

Syntax the compiler complains about an unexpected token ':'.

**Comment by Toilal** [comment]
Do you have lang='ts' in script tag? Did you choose TypeScript when generating the project?

**Comment by MarcoHeumann** [comment]
Woah, fast response time!
Just wanted to update my report with the following:

This issue only happens if i generate the project with "extract html, css and js files in components".
If i keep TS in the vue file the issue is not present.

I did not change ANYTHING at all from the default. You can reproduce this by creating a new project and just using the option to extract js file.

edit: Yes picked typescript.

**Comment by dbettin** [comment]
I see the same issue.  To repeat this happens when you extract out the files.

**Comment by MikaXII** [comment]
Hi same problem here but I add : `lang="ts"` and that compile again with error : 
```log
 I  Your application is running here: http://localhost:8080
ERROR in /Users/mikaxii/workspace/perso/sandbox/my-project/src/router/index.ts(3,24):
TS2306: File '/Users/mikaxii/workspace/perso/sandbox/my-project/src/components/HelloWorld.vue' is not a module.
ERROR in /Users/mikaxii/workspace/perso/sandbox/my-project/test/unit/specs/HelloWorld.spec.ts(2,24):
TS2306: File '/Users/mikaxii/workspace/perso/sandbox/my-project/src/components/HelloWorld.vue' is not a module.
No lint errors found
Version: typescript 2.7.1, tslint 5.9.1
Time: 595ms
```

HelloWorld.vue : 
```html
<template src="./HelloWorld.html">
</template>
<script lang="ts" src="./HelloWorld.ts">
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style  src="./HelloWorld.css" scoped>
</style>
```

EDIT : I think the module issue as the same of #62

**Comment by Toilal** [comment]
Remove .vue extension from import statement in router and tests.

**Comment by MikaXII** [comment]
Yes I just do that and I will notify I fixed the problem XD.
But thanks for your quick response.

For close this issue we just need to add `lang="ts"`when you choose to extract js/css etc to another files
